export const QUESTIONS =   [
    {
      name: 'experience',
      label: 'How would you describe your investment experience?',
      choices: ['Novice', 'Intermediate', 'Advanced'],
      type: 'choice',
      scores: [1, 2, 3],
    },
    {
      name: 'risk_tolerance',
      label: 'How would you rate your risk tolerance?',
      choices: ['Very risk-averse', 'Somewhat risk-averse', 'Moderate', 'Risk-tolerant',],
      type: 'choice',
      scores: [1, 2, 3, 4],
    },
    {
      name: 'investment_goals',
      label: 'What are your primary investment goals?',
      choices: ['Capital preservation', 'Income generation', 'Capital appreciation', 'Speculation'],
      type: 'choice',
      scores: [1, 2, 3, 4],
    },
    {
      name: 'time_horizon',
      label: 'What is your investment time horizon?',
      choices: ['Short-term (less than 1 year)', 'Medium-term (1-5 years)', 'Long-term (more than 5 years)'],
      type: 'choice',
      scores: [1, 2, 3],
    },
    {
      name: 'knowledge',
      label: 'How would you rate your knowledge of financial markets?',
      choices: ['Limited', 'Average', 'Extensive'],
      type: 'choice',
      scores: [1, 2, 3],
    },
    {
      name: 'liquidity_needs',
      label: 'How important is liquidity to you?',
      choices: ['Very important', 'Moderately important', 'Not very important'],
      type: 'choice',
      scores: [1, 2, 3],
    },
    {
      name: 'investment_style',
      label: 'Which investment style best describes you?',
      choices: ['Conservative', 'Moderate', 'Aggressive'],
      type: 'choice',
      scores: [1, 2, 3],
    },
    {
      name: 'income_source',
      label: 'What is your primary source of income?',
      choices: ['Salary/Wages', 'Business/Entrepreneurship', 'Investments', 'Other'],
      type: 'choice',
      scores: [1, 2, 3,4],
    },
    {
      name: 'investment_knowledge',
      label: 'How confident are you in making investment decisions?',
      choices: ['Not confident', 'Somewhat confident', 'Very confident'],
      type: 'choice',
      scores: [1, 2, 3],
    },
    {
      name: 'investment_experience',
      label: 'Have you previously invested in financial markets?',
      choices: ['Yes', 'No'],
      type: 'choice',
      scores: [1, 2],
    },
  ];